packages:
  - notion-flexible-blocks
  - notion-flexible-blocks-example
  - notion-markdown
  - notion-markdown-example
  - migrator-example
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
