services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - 28432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
