import { program } from 'commander'
import { Client } from '@notionhq/client'
import { create } from '@yubrot/notion-markdown'
import { toPageUrl } from '@yubrot/notion-flexible-blocks/util'

await program
  .option('--notion-api-key <key>', 'Notion API Key')
  .argument('<blockId>', 'Target block ID')
  .action(main)
  .parseAsync(process.argv)

async function main(blockId: string, options: { notionApiKey?: string }) {
  const notionApiKey = options.notionApiKey || process.env.NOTION_API_KEY
  if (!notionApiKey) {
    console.error(
      'Notion API Key is required. Please provide it via --notion-api-key or NOTION_API_KEY environment variable.',
    )
    process.exit(1)
  }

  try {
    const client = new Client({ auth: notionApiKey })
    await create(client, blockId, document())
    console.log(toPageUrl(blockId))
  } catch (error) {
    console.error('Failed to create blocks:', error)
    process.exit(1)
  }
}

function document() {
  return `

> [!NOTE]
> THIS PAGE IS GENERATED BY [yubrot/notion-ext/notion-markdown-example](https://github.com/yubrot/notion-ext/tree/main/notion-markdown-example)

# Heading 1

Since there are only three levels of headings in Notion, Headings 4 or later will be treated as Heading 3.

## Heading 2

### Heading 3

#### Heading 4

#### Heading 5

# Text formatting

- Default
- *Italic*
- **Bold**
- ~~Strikethrough~~
- \`Inline code\`

# Paragraphs

私はその人を常に先生と呼んでいた。だからここでもただ先生と書くだけで本名は打ち明けない。これは世間を憚かる遠慮というよりも、その方が私にとって自然だからである。私はその人の記憶を呼び起すごとに、すぐ「先生」といいたくなる。筆を執っても心持は同じ事である。よそよそしい頭文字などはとても使う気にならない。

私が先生と知り合いになったのは鎌倉である。その時私はまだ若々しい書生であった。暑中休暇を利用して海水浴に行った友達からぜひ来いという端書を受け取ったので、私は多少の金を工面して、出掛ける事にした。私は金の工面に二、三日を費やした。ところが私が鎌倉に着いて三日と経たないうちに、私を呼び寄せた友達は、急に国元から帰れという電報を受け取った。電報には母が病気だからと断ってあったけれども友達はそれを信じなかった。友達はかねてから国元にいる親たちに勧まない結婚を強いられていた。彼は現代の習慣からいうと結婚するにはあまり年が若過ぎた。それに肝心の当人が気に入らなかった。それで夏休みに当然帰るべきところを、わざと避けて東京の近くで遊んでいたのである。彼は電報を私に見せてどうしようと相談をした。私にはどうしていいか分らなかった。けれども実際彼の母が病気であるとすれば彼は固より帰るべきはずであった。それで彼はとうとう帰る事になった。せっかく来た私は一人取り残された。
学校の授業が始まるにはまだ大分日数があるので鎌倉におってもよし、帰ってもよいという境遇にいた私は、当分元の宿に留まる覚悟をした。友達は中国のある資産家の息子で金に不自由のない男であったけれども、学校が学校なのと年が年なので、生活の程度は私とそう変りもしなかった。したがって一人ぼっちになった私は別に恰好な宿を探す面倒ももたなかったのである。

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Blocks

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

> ああ、何もかも、ばかばかしい。私は、醜い裏切り者だ。どうとも、勝手にするがよい。やんぬる哉。――四肢を投げ出して、うとうと、まどろんでしまった。
>
> > [太宰治 走れメロス](https://www.aozora.gr.jp/cards/000035/files/1567_14913.html)

\`\`\`markdown
# Code block

- dotted
- lists
- with
  - depth=1
    - depth=2
      - depth=3

1. one
2. two
   1. eleven
   2. twelve
3. three

- [ ] checklist
- [x] checked
\`\`\`

# Lists

- dotted
- lists
- with
  - depth=1
    - depth=2
      - depth=3

1. one
2. two
   1. eleven
   2. twelve
3. three

- [ ] checklist
- [x] checked

# Tables

| Header 1 | Header 2 | Header 3 |
|----------|----------|----------|
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |

# Images

![alt text](https://picsum.photos/300/200.jpg)

---

In Notion, we cannot embed images in paragraphs, so when an image is found in a paragraph, ![](https://picsum.photos/100/100.jpg) the paragraph is split into two paragraphs across the image.

Images in table cells are replaced by the reference strings:

| before | after |
|--------|-------|
| ![](https://picsum.photos/200/100.jpg) | ![](https://picsum.photos/200/120.jpg) |

# Links

- Plain URL: https://www.google.com
- Link to Google: [Link to Google](https://www.google.com)
- Link to Notion page: [Link to Notion page](1e9b53d5317a800593a3de04458c65e5)

# Footnotes

Since Notion does not support footnotes [^1], we will replace them with content [^2] that displays like that.

[^1]: This is a footnote.
[^2]: This is another footnote.
  `
}
